include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - always_declare_return_types
    - always_use_package_imports
    - prefer_final_fields
    - use_function_type_syntax_for_parameters
    - comment_references
