name: passguard_server
description: password manager backend application.
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.5.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.0
  drift: ^2.18.0
  encrypt: ^5.0.3
  fast_rsa: ^3.6.2
  intl: ^0.19.0
  path: ^1.9.0
  pointycastle: ^3.9.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  lints: ^3.0.0
