name: passguard_server
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.2
  dart_jsonwebtoken: ^2.14.0
  drift: ^2.18.0
  intl: ^0.19.0
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  lints: ^3.0.0
  test: ^1.24.0
